deployment:
  strategies:
    canary:
      enabled: true
      initial_weight: 20
      increment: 20
      interval: 300  # seconds
      max_failures: 2
      metrics_threshold:
        error_rate: 1
        latency_p95: 500
    blue_green:
      enabled: true
      health_check_path: /health
      health_check_timeout: 30
      rollback_timeout: 300
    rolling:
      enabled: true
      max_surge: 25%
      max_unavailable: 25%
  validation:
    required: true
    timeout: 60
    endpoints:
      - /health
      - /metrics
      - /ready
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi