incident_response:
  auto_remediation:
    enabled: true
    max_attempts: 3
    blackout_period: 300
  classification:
    model_type: random_forest
    confidence_threshold: 0.8
    features:
      - error_rate
      - response_time
      - cpu_usage
      - memory_usage
  escalation:
    levels:
      - level: 1
        timeout: 900
        notifiers:
          - devops-team
      - level: 2
        timeout: 1800
        notifiers:
          - sre-team
      - level: 3
        timeout: 3600
        notifiers:
          - management
  runbooks:
    enabled: true
    repository: https://github.com/company/runbooks