security:
  scanning:
    enabled: true
    interval: 86400  # daily
    fail_on_critical: true
    scanners:
      - vulnerability
      - compliance
      - configuration
      - secret
  compliance:
    standards:
      - PCI-DSS
      - HIPAA
      - SOC2
      - GDPR
    checks:
      encryption:
        required: true
        algorithms:
          - AES-256
          - RSA-2048
      authentication:
        mfa_required: true
        session_timeout: 3600
  vulnerability_management:
    auto_fix: false
    ignore_list:
      - CVE-2023-XXXX
    severity_threshold: medium
  network:
    allowed_ips:
      - 10.0.0.0/8
      - 172.16.0.0/12
    restricted_ports:
      - 22
      - 3389